/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  //The safelist option in the Tailwind CSS configuration file is used to prevent 
  //certain classes from being purged when you build your project for production.
  // Like classes that are dynamically generated by JavaScript and the purge process
  // can't detect (Tailwind uses PurgeCSS under the hood)
  // Be careful when using this option, as it can easily lead to a bloated CSS file
  // and make Next.js compile times very slow.
  safelist: [],
  plugins: [],
}
